# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Docker

on:
  workflow_call:
    secrets:
      REGISTRY_USER:
        required: true
      REGISTRY_TOKEN:
        required: true

env:
  APP: ${{ github.event.repository.name }}
  IMAGE_NAME: eria/${{ github.event.repository.name }}
  REGISTRY: rg.fr-par.scw.cloud

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        # go-version: 1.20 // means 1.2.0

    - name: Git History # Retrieves the necessary historical information
      id: ghd
      uses: proudust/gh-describe@v1

    - name: Git ENV
      shell: bash
      run: |
        echo "describe: ${{ steps.ghd.outputs.describe }}"
        echo "tag     : ${{ steps.ghd.outputs.tag }}"
        echo "distance: ${{ steps.ghd.outputs.distance }}"
        echo "sha     : ${{ steps.ghd.outputs.sha }}"
        echo "GIT_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "GIT_TAG=${{ steps.ghd.outputs.describe }}" >> $GITHUB_ENV
        echo "GIT_BRANCH=$(git symbolic-ref -q --short HEAD)" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M')" >> $GITHUB_ENV

    - name: Generate TAGS (stable)
      if: github.ref_type == 'tag'
      shell: bash
      run: |
        echo "TAG1=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV
        echo "TAG2=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.GIT_TAG }}" >> $GITHUB_ENV

    - name: Generate TAGS (dev)
      if: github.ref_type != 'tag'
      shell: bash
      run: |
        echo "TAG1=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev" >> $GITHUB_ENV
        echo "TAG2=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.GIT_SHA_SHORT }}-${{ env.GIT_BRANCH }}" >> $GITHUB_ENV

    - name: Show GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Build && Push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/arm/v7,linux/arm/v6,linux/amd64,linux/arm64
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.TAG1 }}
          ${{ env.TAG2 }}
        build-args: |
          VERSION=${{ env.GIT_TAG }}
          BUILDDATE=${{ env.BUILD_DATE }}

    - name: Show details of image in the registry
      run: |
        docker buildx imagetools inspect "${{ env.TAG1 }}"
