# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: GoReleaser

on:
  workflow_call:

env:
  APP: ${{ github.event.repository.name }}
  IMAGE_NAME: project-eria/${{ github.event.repository.name }}
  REGISTRY: rg.fr-par.scw.cloud

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Get GoReleaser config
      uses: wei/curl@v1
      with:
        args: -o .goreleaser.yaml https://raw.githubusercontent.com/project-eria/workflows/main/.github/goreleaser.yaml

    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}